services:
    nginx:
      image: nginx:latest
      ports:
        - "0.0.0.0:80:80"
        - "0.0.0.0:443:443" 
      volumes:
        - "./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf"
        - "/etc/certs:/etc/nginx/certs"
      depends_on:
      - webserver
    webserver:
      build:
        dockerfile: Dockerfile
        context: ./http-echo
      command: -listen=:8000 -text=hello 
      ports:
        - '127.0.0.1:8000:8000'
